### ISSUE TITLE
Unsatisfiable dependencies for platform linux-64

### ISSUE THREAD

**Issue by ravinpoudel** [gagan3012/streamlit-tags#24]
I am planning to submit a package to bioconda, which failing and got the following error. Any suggestion on how to fix it?

```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"streamlit-tags[version='>=1.1.9']"}

```

**Comment by gagan3012** [comment]
Can you add this command in too?
```
conda config --add channels gagan3012
```

**Comment by ravinpoudel** [comment]
Following is my `meta.yml` file for Bioconda recipe. Should I pass the channel info after the script section?

```
{% set version = "0.2.0" %}
{% set name = "GuideMaker" %}
{% set sha256 = "c9cb6e35844209259159ee0530390d837748678538b6a9ed7e71645ba51d57be" %}
{% set user = "USDA-ARS-GBRU" %}


package:
  name: '{{ name|lower }}'
  version: '{{ version }}'


source:
  url: https://github.com/{{ user }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 1
  noarch: python
  entry_points:
    - guidemaker=guidemaker.cli:main
  script: python -m pip install --no-deps --ignore-installed .


requirements:
  host:
    - pip
    - python >=3.6
    - biopython==1.76
  run:
    - pip
    - python >=3.6
    - biopython==1.76
    - biopython==1.76
    - numpy >=1.13
    - pybedtools==0.8.2
    - nmslib>=2.0.6
    - pandas>=1.0.0
    - pyyaml>=5.4.1
    - regex==2020.11.13
    - altair
    - streamlit>0.80.0
    - pytest>=4.6
    - pytest-cov
    - streamlit-tags>=1.1.9
    - pdoc3


test:
  commands:
    - {{ name }} --version | grep '{{ version }}'
    - {{ name }} --help



about:
  home: https://github.com/USDA-ARS-GBRU/GuideMaker
  license: 'CC0 1.0'
  license_family: 'PUBLIC-DOMAIN'
  license_file: LICENSE.txt
  summary: 'GuideMaker: Software to design gRNAs pools in non-model genomes and CRISPR-Cas systems'


extra:
  recipe-maintainers:
    - arivers
    - ravinpoudel
  identifiers:
    - biotools:GuideMaker
    - doi:10.5281/zenodo.4849258

```
